"""Show successfully tested OmniRoute models ordered by fastest response.

Reads test_state.json generated by test_all_models.py.
Usage:
    python work-model.py
    python work-model.py --limit 20
    python work-model.py --json
"""
from __future__ import annotations

import argparse
import json
import os
from datetime import datetime

STATE_FILE = "test_state.json"
OUTPUT_FILE = "work_models.json"


def load_state():
    if not os.path.exists(STATE_FILE):
        raise SystemExit(
            f"{STATE_FILE} tidak ditemukan. Jalankan test_all_models.py terlebih dahulu."
        )

    try:
        with open(STATE_FILE, encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError) as exc:
        raise SystemExit(f"Gagal membaca {STATE_FILE}: {exc}")

    if not isinstance(data, dict) or not isinstance(data.get("models"), dict):
        raise SystemExit(f"Format {STATE_FILE} tidak valid.")

    return data


def build_work_models(state):
    result = []

    for model, info in state["models"].items():
        if not isinstance(info, dict):
            continue

        # Hanya model yang benar-benar berhasil merespons.
        if info.get("status") != "OK":
            continue

        latency = info.get("latency")
        if not isinstance(latency, (int, float)):
            continue

        result.append(
            {
                "rank": 0,
                "model": model,
                "latency": float(latency),
                "tier": info.get("tier", "UNKNOWN"),
                "detail": info.get("detail", ""),
                "tested_at": info.get("tested_at"),
                "attempts": info.get("attempts", 1),
                "tools": info.get("tools"),
            }
        )

    result.sort(key=lambda item: (item["latency"], item["model"].lower()))

    for rank, item in enumerate(result, 1):
        item["rank"] = rank

    return result


def save_json(models):
    payload = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "total_work_models": len(models),
        "models": models,
    }

    tmp = OUTPUT_FILE + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)

    os.replace(tmp, OUTPUT_FILE)


def main():
    parser = argparse.ArgumentParser(
        description="Tampilkan model OK berdasarkan response tercepat."
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=0,
        help="Jumlah model yang ditampilkan. 0 = semua.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Tampilkan hasil sebagai JSON.",
    )
    args = parser.parse_args()

    if args.limit < 0:
        parser.error("--limit tidak boleh negatif")

    state = load_state()
    models = build_work_models(state)

    shown = models[: args.limit] if args.limit else models

    save_json(models)

    if args.json:
        print(json.dumps(shown, ensure_ascii=False, indent=2))
        return

    print()
    print("=== WORK MODELS ===")
    print(f"Berhasil : {len(models)} model")
    print(f"Ditampilkan : {len(shown)} model")
    print()

    if not shown:
        print("Belum ada model dengan status OK.")
        print("Jalankan: python test_all_models.py --workers 2")
        return

    print(f"{'#':<5} {'Latency':<10} Model")
    print("-" * 72)

    for item in shown:
        print(
            f"{item['rank']:<5} "
            f"{item['latency']:.1f}s".ljust(10)
            + f" {item['model']}"
        )

    print()
    print(f"Disimpan ke: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
